import { describe, expect, it } from 'vitest';
import { colorizeRgba } from './colorize';

// Captured from Qt 6.11.1 QGraphicsColorizeEffect(strength=1), not generated by this implementation.
const inputs = [ [0, 0, 0, 255], [255, 255, 255, 255], [60, 130, 210, 255],
  [255, 0, 0, 255], [0, 255, 0, 255], [0, 0, 255, 255], [60, 130, 210, 170], [60, 130, 210, 64], [60, 130, 210, 0] ];
describe('Qt strength=1 非白像素染色参考', () => {
  it.each([
    ['#50a9ee', [[80,169,238,255],[255,255,255,255],[161,209,246,255],[140,198,244,255],[167,212,246,255],[107,182,241,255],[134,197,243,170],[100,179,239,64],[0,0,0,0]]],
    ['#ff795e', [[255,121,94,255],[255,255,255,255],[255,183,169,255],[255,167,149,255],[255,188,174,255],[255,141,119,255],[255,164,144,170],[255,135,112,64],[0,0,0,0]]],
    ['#2e6189', [[46,97,137,255],[255,255,255,255],[143,170,192,255],[117,151,177,255],[150,176,196,255],[78,121,155,255],[111,146,174,170],[72,116,151,64],[0,0,0,0]]],
  ] as const)('颜色%s的9个RGBA参考向量均匹配且不改原图', (color, expected) => {
    const source = new Uint8ClampedArray(inputs.flat());
    expect([...colorizeRgba(source, color)]).toEqual(expected.flat());
    expect([...source]).toEqual(inputs.flat());
  });
  it('拒绝非法像素长度及颜色，不静默生成误导预览', () => {
    expect(() => colorizeRgba(new Uint8ClampedArray(3), '#50a9ee')).toThrow();
    expect(() => colorizeRgba(new Uint8ClampedArray(4), 'invalid')).toThrow();
  });
});
